//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_WAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        public int attendeeID { get; set; }
        public string purchaseDate { get; set; }
        public string purchaseTime { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string sessionID { get; set; }
        public string transactionID { get; set; }
        public string ticketQty { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
    }
}
