//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_WAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int eventID { get; set; }
        public string eventCategory { get; set; }
        public string eventLogo { get; set; }
        public string eventDescription { get; set; }
        public string eventLocation { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public string eventTime { get; set; }
        public Nullable<decimal> eventCost { get; set; }
    }
}
